{- ORMOLU_DISABLE -}

{-# LANGUAGE OverloadedStrings #-}

-- This module is generated by `./th/main.py --install` (whenever
-- th/data.json changes). Hence do not edit this file!
module JsonData where

import Data.Text

jsonData :: Text
jsonData = "{\n\
         \  \"creatures\": [\n\
         \    { \"id\": { \"name\":\"spearman\",  \"team\":\"human\" },  \"title\":\"Spearman\",  \"hp\":2, \"attack\":1, \"moral\":3, \"victory_points\":2, \"filepath\": {\"root\": \"24x24\", \"x\": 1, \"y\": 0}, \"skills\":[\"LongReach\"] },\n\
         \    { \"id\": { \"name\":\"swordsman\", \"team\":\"human\" },  \"title\":\"swordsman\", \"hp\":2, \"attack\":1, \"moral\":3, \"victory_points\":2, \"filepath\": {\"root\": \"24x24\", \"x\": 0, \"y\": 0} },\n\
         \    { \"id\": { \"name\":\"archer\",    \"team\":\"human\" },  \"title\":\"archer\",    \"hp\":2, \"attack\":1, \"moral\":3, \"victory_points\":2, \"filepath\": {\"root\": \"24x24\", \"x\": 2, \"y\": 0}, \"skills\":[\"Ranged\"] },\n\
         \    { \"id\": { \"name\":\"general\",   \"team\":\"human\" },  \"title\":\"general\",   \"hp\":3, \"attack\":3, \"moral\":5, \"victory_points\":5, \"filepath\": {\"root\": \"24x24\", \"x\": 3, \"y\": 0}, \"skills\":[\"Leader\", \"Unique\"] },\n\
         \    { \"id\": { \"name\":\"knight\",    \"team\":\"human\" },  \"title\":\"Knight\",    \"hp\":2, \"attack\":2, \"moral\":4, \"victory_points\":5, \"filepath\": {\"root\": \"24x24\", \"x\": 4, \"y\": 0}, \"skills\":[\"Stubborn\"] },\n\
         \    { \"id\": { \"name\":\"skeleton\",  \"team\":\"undead\" }, \"title\":\"skeleton\",  \"hp\":1, \"attack\":1, \"victory_points\":1, \"filepath\": {\"root\": \"24x24\", \"x\": 0, \"y\": 3} },\n\
         \    { \"id\": { \"name\":\"vampire\",   \"team\":\"undead\" }, \"title\":\"vampire\",   \"hp\":3, \"attack\":3, \"victory_points\":5, \"filepath\": {\"root\": \"24x24\", \"x\": 1, \"y\": 3} },\n\
         \    { \"id\": { \"name\":\"archer\",    \"team\":\"undead\" }, \"title\":\"archer\",    \"hp\":1, \"attack\":1, \"victory_points\":1, \"filepath\": {\"root\": \"24x24\", \"x\": 2, \"y\": 3}, \"skills\":[\"Ranged\"]},\n\
         \    { \"id\": { \"name\":\"mummy\",     \"team\":\"undead\" }, \"title\":\"mummy\",     \"hp\":5, \"attack\":2, \"victory_points\":2, \"filepath\": {\"root\": \"24x24\", \"x\": 3, \"y\": 3}},\n\
         \    { \"id\": { \"name\":\"warrior\",   \"team\":\"undead\" }, \"title\":\"warrior\",   \"hp\":1, \"attack\":2, \"victory_points\":0, \"filepath\": {\"root\": \"24x24\", \"x\": 4, \"y\": 3}},\n\
         \    { \"id\": { \"name\":\"ghost\",     \"team\":\"undead\" }, \"title\":\"ghost\",     \"hp\":1, \"attack\":0, \"victory_points\":0, \"filepath\": {\"root\": \"24x24\", \"x\": 5, \"y\": 3}},\n\
         \    { \"id\": { \"name\":\"shade\",     \"team\":\"undead\" }, \"title\":\"shade\",     \"hp\":1, \"attack\":2, \"victory_points\":0, \"filepath\": {\"root\": \"24x24\", \"x\": 6, \"y\": 3}}\n\
         \  ],\n\
         \  \"neutral\": [\n\
         \    { \"name\":\"health\", \"title\":\"Health\", \"tile\":\"RedPotion\",   \"text\":\"Heals 1 HP\" },\n\
         \    { \"name\":\"life\",   \"title\":\"Life\",   \"tile\":\"GreenPotion\", \"text\":\"Restores all HP\" }\n\
         \  ],\n\
         \  \"items\": [\n\
         \    { \"name\":\"crown\", \"title\":\"Crown\", \"tile\":\"crown\", \"text\":\"Leadership +2\" }\n\
         \  ],\n\
         \  \"tiles\": [\n\
         \    { \"tile\":\"BlackAppears0\", \"filepath\": { \"root\": \"24x24\", \"x\":0, \"y\":6 } },\n\
         \    { \"tile\":\"BlackAppears1\", \"filepath\": { \"root\": \"24x24\", \"x\":1, \"y\":6 } },\n\
         \    { \"tile\":\"BlackAppears2\", \"filepath\": { \"root\": \"24x24\", \"x\":2, \"y\":6 } },\n\
         \    { \"tile\":\"BlackAppears3\", \"filepath\": { \"root\": \"24x24\", \"x\":3, \"y\":6 } },\n\
         \    { \"tile\":\"Blood0\",        \"filepath\": { \"root\": \"24x24\", \"x\":0, \"y\":7 } },\n\
         \    { \"tile\":\"Blood1\",        \"filepath\": { \"root\": \"24x24\", \"x\":1, \"y\":7 } },\n\
         \    { \"tile\":\"Blood2\",        \"filepath\": { \"root\": \"24x24\", \"x\":2, \"y\":7 } },\n\
         \    { \"tile\":\"Blood3\",        \"filepath\": { \"root\": \"24x24\", \"x\":3, \"y\":7 } },\n\
         \    { \"tile\":\"Bones0\",        \"filepath\": { \"root\": \"24x24\", \"x\":0, \"y\":8 } },\n\
         \    { \"tile\":\"Bones1\",        \"filepath\": { \"root\": \"24x24\", \"x\":1, \"y\":8 } },\n\
         \    { \"tile\":\"Bones2\",        \"filepath\": { \"root\": \"24x24\", \"x\":2, \"y\":8 } },\n\
         \    { \"tile\":\"Bones3\",        \"filepath\": { \"root\": \"24x24\", \"x\":3, \"y\":8 } },\n\
         \    { \"tile\":\"Bones4\",        \"filepath\": { \"root\": \"24x24\", \"x\":4, \"y\":8 } },\n\
         \    { \"tile\":\"Bones5\",        \"filepath\": { \"root\": \"24x24\", \"x\":5, \"y\":8 } },\n\
         \    { \"tile\":\"Bones6\",        \"filepath\": { \"root\": \"24x24\", \"x\":6, \"y\":8 } },\n\
         \    { \"tile\":\"Heart\",         \"filepath\": { \"root\": \"16x16\", \"x\":0, \"y\":0 } },\n\
         \    { \"tile\":\"Sword1\",        \"filepath\": { \"root\": \"16x16\", \"x\":1, \"y\":0 } },\n\
         \    { \"tile\":\"Sword2\",        \"filepath\": { \"root\": \"16x16\", \"x\":3, \"y\":1 } },\n\
         \    { \"tile\":\"RedPotion\",     \"filepath\": { \"root\": \"16x16\", \"x\":2, \"y\":0 } },\n\
         \    { \"tile\":\"GreenPotion\",   \"filepath\": { \"root\": \"16x16\", \"x\":3, \"y\":0 } },\n\
         \    { \"tile\":\"Crown\",         \"filepath\": { \"root\": \"16x16\", \"x\":0, \"y\":1 } },\n\
         \    { \"tile\":\"Loupe\",         \"filepath\": { \"root\": \"16x16\", \"x\":4, \"y\":1 } },\n\
         \    { \"tile\":\"WhiteAppears0\", \"filepath\": { \"root\": \"24x24\", \"x\":0, \"y\":5 } },\n\
         \    { \"tile\":\"WhiteAppears1\", \"filepath\": { \"root\": \"24x24\", \"x\":1, \"y\":5 } },\n\
         \    { \"tile\":\"WhiteAppears2\", \"filepath\": { \"root\": \"24x24\", \"x\":2, \"y\":5 } },\n\
         \    { \"tile\":\"WhiteAppears3\", \"filepath\": { \"root\": \"24x24\", \"x\":3, \"y\":5 } },\n\
         \    { \"tile\":\"WhiteAppears4\", \"filepath\": { \"root\": \"24x24\", \"x\":4, \"y\":5 } }\n\
         \  ],\n\
         \  \"skills\": [\n\
         \    { \"skill\":\"LongReach\",   \"title\":\"Long reach\", \"text\":\"hits 2 cells away when in the back line\"},\n\
         \    { \"skill\":\"Leader\",      \"title\":\"Leadership\", \"text\":\"adjacent allies get +2 moral upon arrival\"},\n\
         \    { \"skill\":\"Ranged\",      \"title\":\"Ranged\",     \"text\":\"hits any enemy in its column\"},\n\
         \    { \"skill\":\"Stubborn\",    \"title\":\"Stubborn\",   \"text\":\"if alone, ignores first wound every turn\"},\n\
         \    { \"skill\":\"Unique\",      \"title\":\"Unique\",     \"text\":\"discarded after kill\"}\n\
         \  ]\n\
         \}\n"
