name: "build, test"
on:
  pull_request:
  push:
defaults:
  run:
    working-directory: ./app
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run 'cabal build app.cabal:app'
    - run: nix-shell --run 'cabal test'
