name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install linters
      run: |
        sudo apt install jsonlint python3-pip
        # pip install -r $GITHUB_WORKSPACE/hooks/requirements.txt

    - name: jsonlint-php th/data.json
      run: jsonlint-php $GITHUB_WORKSPACE/th/data.json

    - name: lint hooks/pre-commit.py
      run: |
        # mypy        $GITHUB_WORKSPACE/hooks/pre-commit.py
        # pycodestyle $GITHUB_WORKSPACE/hooks/pre-commit.py
        # pylint      $GITHUB_WORKSPACE/hooks/pre-commit.py
