name: "lint"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install linters
      run: |
        sudo apt install jsonlint python3-pip shellcheck
        # pip install -r $GITHUB_WORKSPACE/hooks/requirements.txt
    - name: jsonlint-php th/data.json
      run: jsonlint-php $GITHUB_WORKSPACE/th/data.json
    - name: shellcheck
      run: |
        shellcheck --version
        shellcheck $(git ls-files "*.sh" | grep -v 'load-n-reload\|dl-large-assets\|install-hls')
    - name: import qualification
      run: |
        ./scripts/check-imports.sh
